<a href="https://colab.research.google.com/github/Shraghav/GIT/blob/main/Assesement1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1) Create a list and a tuple. Perform the following operations in the created list and tuple.

In [ ]:
#a) accessing elements
a=[100,20,80,36,40]
b=(1,2,3,4,5,6,7)
print(a[1],b[2])

20 3


In [ ]:
#b) updating existing with new item
a[2]=99
print(a)

[100, 20, 99, 36, 40]


In [ ]:
#c) loop through list and tuple
print("List elements:")
for i in a:
  print(i)
print("Tuple elements:")
for j in b:
  print(j)

List elements:
100
20
99
36
40
Tuple elements:
1
2
3
4
5
6
7


In [ ]:
#d) sort, copy , join list
a.sort()
print(a)

copy_a=a.copy()
print(a)

c=[89,97,34,58]
a.extend(c)
print(a)

[20, 36, 40, 99, 100]
[20, 36, 40, 99, 100]
[20, 36, 40, 99, 100, 89, 97, 34, 58]


In [ ]:
#e) join tuple
tup_1=(1,5,2,6)
tup_2=(8,9,5,4)
print(tup_1+tup_2)

(1, 5, 2, 6, 8, 9, 5, 4)


2. Create a set and a dictionary. Perform the following operations in the created set and
dictionary.

In [ ]:
#a) access and change elements
dict_a={"Name":"Raghavan","Department":"AI&DS","Year":"2nd","College":"BIT","Home Town":"Coimbatore"}
print(dict_a)
dict_a['Name']="Harish"
print(dict_a)

{'Name': 'Raghavan', 'Department': 'AI&DS', 'Year': '2nd', 'College': 'BIT', 'Home Town': 'Coimbatore'}
{'Name': 'Harish', 'Department': 'AI&DS', 'Year': '2nd', 'College': 'BIT', 'Home Town': 'Coimbatore'}


In [ ]:
#b) add and remove elements
dict_a["Year"]="2nd"
dict_a["Hobby"]="Relaxing"
print(dict_a)
del dict_a["Year"]


{'Name': 'Harish', 'Department': 'AI&DS', 'Year': '2nd', 'College': 'BIT', 'Home Town': 'Coimbatore', 'Hobby': 'Relaxing'}


In [ ]:
#c) loop through dictionary and copy
for k in dict_a.values():
  print(k)
copy_dict=dict_a.copy()
print(copy_dict)

Harish
AI&DS
BIT
Coimbatore
Relaxing
{'Name': 'Harish', 'Department': 'AI&DS', 'College': 'BIT', 'Home Town': 'Coimbatore', 'Hobby': 'Relaxing'}


In [ ]:
#d) nested dictionary
nested={1:{11:"Hello",12:"Dude"},2:"Happy",3:"Man"}
print(nested[1])

{11: 'Hello', 12: 'Dude'}


3. Use Numpy python library to perform the following operations.

In [10]:
#a) create array
import numpy as np 
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [13]:
#b)array indexing and slicing
print(arr[2])
print(arr[1:4])
print(arr[2:])
print(arr[-2:])
print(arr[:4:2])

3
[2 3 4]
[3 4 5]
[4 5]
[1 3]


In [14]:
#c) joining and splitting array
new_arr=np.array([23,45,64,32])
add=np.concatenate((arr,new_arr))
print(add)

newarr = np.array_split(arr, 3)
print(newarr)


[ 1  2  3  4  5 23 45 64 32]
[array([1, 2]), array([3, 4]), array([5])]


In [15]:
arr1 = np.array([10, 3, 5, 8, 1])
#d) sorting and searching
sorted_arr = np.sort(arr1)
print("Sorted Array:", sorted_arr)


Sorted Array: [ 1  3  5  8 10]


4) Create a CSR matrix using SciPy and convert the same into CSC matrix.

In [17]:
import numpy as np
from scipy.sparse import csr_matrix, csc_matrix

#dense matrix
dense = np.array([[1, 0, 0, 2], [0, 1, 3, 0], [4, 3, 0, 5]])

#dense matrix to a CSR matrix
csr = csr_matrix(dense)

#CSR matrix to a CSC matrix
csc = csc_matrix(csr)

print("CSR matrix:")
print(csr.toarray())

print("CSC matrix:")
print(csc.toarray())


CSR matrix:
[[1 0 0 2]
 [0 1 3 0]
 [4 3 0 5]]
CSC matrix:
[[1 0 0 2]
 [0 1 3 0]
 [4 3 0 5]]


5) With python Pandas, perform the following data cleaning operations

In [23]:
#a) Upload the cereals.csv dataset (Refer attachment) and print only the first 5 row
#and last 7 rows from the dataset.
import pandas as pd
df=pd.read_csv('cereal.csv')
print("First 5 elements:")
print(df.head())
print("Last 7 elements:")
df.tail(7)

First 5 elements:
                        name mfr type  calories  protein  fat  sodium  fiber  \
0                  100% Bran   N    C        70        4    1     130   10.0   
1          100% Natural Bran   Q    C       120        3    5      15    2.0   
2                   All-Bran   K    C        70        4    1     260    9.0   
3  All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4             Almond Delight   R    C       110        2    2     200    1.0   

   carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
0    5.0       6     280        25      3     1.0  0.33  68.402973  
1    8.0       8     135         0      3     1.0  1.00  33.983679  
2    7.0       5     320        25      3     1.0  0.33  59.425505  
3    8.0       0     330        25      3     1.0  0.50  93.704912  
4   14.0       8      -1        25      3     1.0  0.75  34.384843  
Last 7 elements:


name mfr type  calories  protein  fat  sodium  fiber  \
70    Total Raisin Bran   G    C       140        3    1     190    4.0   
71    Total Whole Grain   G    C       100        3    1     200    3.0   
72              Triples   G    C       110        2    1     250    0.0   
73                 Trix   G    C       110        1    1     140    0.0   
74           Wheat Chex   R    C       100        3    1     230    3.0   
75             Wheaties   G    C       100        3    1     200    3.0   
76  Wheaties Honey Gold   G    C       110        2    1     200    1.0   

    carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
70   15.0      14     230       100      3     1.5  1.00  28.592785  
71   16.0       3     110       100      3     1.0  1.00  46.658844  
72   21.0       3      60        25      3     1.0  0.75  39.106174  
73   13.0      12      25        25      2     1.0  1.00  27.753301  
74   17.0       3     115        25      1     1.0  0.67  49.787445  
75   17.0       3     110        25      1     1.0  1.00  51.592193  
76   16.0       8      60        25      1     1.0  0.75  36.187559

In [24]:
#b) description of the event
df.describe()

calories    protein        fat      sodium      fiber      carbo  \
count   77.000000  77.000000  77.000000   77.000000  77.000000  77.000000   
mean   106.883117   2.545455   1.012987  159.675325   2.151948  14.597403   
std     19.484119   1.094790   1.006473   83.832295   2.383364   4.278956   
min     50.000000   1.000000   0.000000    0.000000   0.000000  -1.000000   
25%    100.000000   2.000000   0.000000  130.000000   1.000000  12.000000   
50%    110.000000   3.000000   1.000000  180.000000   2.000000  14.000000   
75%    110.000000   3.000000   2.000000  210.000000   3.000000  17.000000   
max    160.000000   6.000000   5.000000  320.000000  14.000000  23.000000   

          sugars      potass    vitamins      shelf     weight       cups  \
count  77.000000   77.000000   77.000000  77.000000  77.000000  77.000000   
mean    6.922078   96.077922   28.246753   2.207792   1.029610   0.821039   
std     4.444885   71.286813   22.342523   0.832524   0.150477   0.232716   
min    -1.000000   -1.000000    0.000000   1.000000   0.500000   0.250000   
25%     3.000000   40.000000   25.000000   1.000000   1.000000   0.670000   
50%     7.000000   90.000000   25.000000   2.000000   1.000000   0.750000   
75%    11.000000  120.000000   25.000000   3.000000   1.000000   1.000000   
max    15.000000  330.000000  100.000000   3.000000   1.500000   1.500000   

          rating  
count  77.000000  
mean   42.665705  
std    14.047289  
min    18.042851  
25%    33.174094  
50%    40.400208  
75%    50.828392  
max    93.704912

In [28]:
#c) Create a new dataset from cereals.csv by removing some values in the
#attributes ‘calories’, ‘fat’ and ‘sugars’. Print the new dataset.
df.drop(df.columns[[3,5,9]],axis=1,inplace=True)
df

name mfr type  sodium  carbo  potass  vitamins  \
0                   100% Bran   N    C     130    5.0     280        25   
1           100% Natural Bran   Q    C      15    8.0     135         0   
2                    All-Bran   K    C     260    7.0     320        25   
3   All-Bran with Extra Fiber   K    C     140    8.0     330        25   
4              Almond Delight   R    C     200   14.0      -1        25   
..                        ...  ..  ...     ...    ...     ...       ...   
72                    Triples   G    C     250   21.0      60        25   
73                       Trix   G    C     140   13.0      25        25   
74                 Wheat Chex   R    C     230   17.0     115        25   
75                   Wheaties   G    C     200   17.0     110        25   
76        Wheaties Honey Gold   G    C     200   16.0      60        25   

    weight  cups     rating  
0      1.0  0.33  68.402973  
1      1.0  1.00  33.983679  
2      1.0  0.33  59.425505  
3      1.0  0.50  93.704912  
4      1.0  0.75  34.384843  
..     ...   ...        ...  
72     1.0  0.75  39.106174  
73     1.0  1.00  27.753301  
74     1.0  0.67  49.787445  
75     1.0  1.00  51.592193  
76     1.0  0.75  36.187559  

[77 rows x 10 columns]

In [33]:
dd=pd.read_csv('cereal.csv')
dd['calories'].fillna(value=95, inplace=True)
dd['fat'].fillna(value=dd['fat'].mean(), inplace=True)
dd['sugars'].fillna(value=dd['sugars'].median(), inplace=True)
dd

name mfr type  calories  protein  fat  sodium  fiber  \
0                   100% Bran   N    C        70        4    1     130   10.0   
1           100% Natural Bran   Q    C       120        3    5      15    2.0   
2                    All-Bran   K    C        70        4    1     260    9.0   
3   All-Bran with Extra Fiber   K    C        50        4    0     140   14.0   
4              Almond Delight   R    C       110        2    2     200    1.0   
..                        ...  ..  ...       ...      ...  ...     ...    ...   
72                    Triples   G    C       110        2    1     250    0.0   
73                       Trix   G    C       110        1    1     140    0.0   
74                 Wheat Chex   R    C       100        3    1     230    3.0   
75                   Wheaties   G    C       100        3    1     200    3.0   
76        Wheaties Honey Gold   G    C       110        2    1     200    1.0   

    carbo  sugars  potass  vitamins  shelf  weight  cups     rating  
0     5.0       6     280        25      3     1.0  0.33  68.402973  
1     8.0       8     135         0      3     1.0  1.00  33.983679  
2     7.0       5     320        25      3     1.0  0.33  59.425505  
3     8.0       0     330        25      3     1.0  0.50  93.704912  
4    14.0       8      -1        25      3     1.0  0.75  34.384843  
..    ...     ...     ...       ...    ...     ...   ...        ...  
72   21.0       3      60        25      3     1.0  0.75  39.106174  
73   13.0      12      25        25      2     1.0  1.00  27.753301  
74   17.0       3     115        25      1     1.0  0.67  49.787445  
75   17.0       3     110        25      1     1.0  1.00  51.592193  
76   16.0       8      60        25      1     1.0  0.75  36.187559  

[77 rows x 16 columns]